[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "14.21.2" }
  functions = "netlify/funciones"
  
[build.environment]
  NODE_VERSION = "14"
  YARN_VERSION = "1.222.5"
  NPM_VERSION = "6.14.6"